### ISSUE TITLE
Parsing process progress

### ISSUE THREAD

**Issue by BOPOHOB** [SteveDoyle2/pyNastran#179]
Hello. I wish to use pyNastran for parse BDF in my program which is based on Qt (not pySide). Currently I execute parser as an external application. I use standart sys.stdin/out as a way to transmit data from/to C++ part of program. But it's imposible to get ainy information about progress while BDF.read_bdf(..) is running. Do you have any ideas how to get this information?

**Comment by SteveDoyle2** [comment]
The default logging object prints to standard out because I'm not good with the logging module.  You should just be able to capture that stream.  The one issue I see is Python buffers the print statements, so you may need to write a custom logger.  You might also not be getting the log updating frequently enough depending on info/debug, but adding a print card/icard every 1000/user-selectable number of cards seems ok.

If you use the test_bdf method, you should be getting at least a few messages (I think you'll get info messages only using it), but you should definitely get something.

Also, can you explain how you're using the parser since you need to get the data from Python into C++?

**Comment by SteveDoyle2** [comment]
Also, your "custom" logger could be as simple as taking the hackish one in pyNastran and adding a sys.stdout.flush() to it after each print.

**Comment by SteveDoyle2** [comment]
closing due to innactivity

**Comment by BOPOHOB** [comment]
Sorry about huge delay of  response. 
https://github.com/NII-APP/NPO/blob/master/NPO/readBDF.py there is a python part of code. 
In c++ side code is distributed in different files but main loop of reading  defined in scarfUp function in this file https://github.com/NII-APP/NPO/blob/master/NPO/engine/geometry.cpp
