### ISSUE TITLE
http://code.google.com/p/pynastran/wiki/OP2 seems to be outdated

### ISSUE THREAD

**Issue by nilswagner** [SteveDoyle2/pyNastran#184]

**Comment by SteveDoyle2** [comment]
The wiki references the current released version unless otherwise stated, which is v0.6.1

Additionally, due to the coming shutdown and migration, anything on http://code.google.com will not be improved and will soon be removed.  The wiki is now located at:

https://github.com/SteveDoyle2/pyNastran/wiki

It's still in work.  Some pages are missing.  Some links are broken and formatting isn't perfect, but it will be updated for v0.7.
