### ISSUE TITLE
Specific cross-referencing

### ISSUE THREAD

**Issue by Ravi2015** [SteveDoyle2/pyNastran#190]
Hi Steve and others!

I was wondering if it's possible to cross-reference nodes, co-ordinates and elements only. 

Currently, if xref is set to 'true', then pyNastran tries to cross-reference nodes, co-ordinates, elements, plus, properties, materials, aero, constraints, loads, etc. (looking at the cross_reference method in crossReference.py file)

I think it would be nice if an advanced user had control on what items are cross-referenced. For e.g. currently I need only the geometry info and nodes and elements to be cross-referenced and I don't really care about the elements and properties being linked up, etc.

**Comment by SteveDoyle2** [comment]
Things like this have thrown around, but not so clearly...so yes.  Just note that cross referencing is kind of important, so buyer beware.

v0.7 already supports:

    model = BDF()
    model.read_bdf(bdf_filename, xref=False)
    model.cross_reference(xref=True, xref_loads=True, xref_constraints=True)

How is just adding xref_materials, xref_elements, xref_properties, xref_aero, and xref_masses to the cross_reference method?  I don't want to set nodes/coordinates as separate xrefs as they're tied together pretty tightly.  For your problem, I'm thinking...

    model.cross_reference(xref=True, xref_loads=False, xref_constraints=False,
    xref_materials=False, xref_properties=False, xref_aero=False, xref_masses=False)

Any other ideas on how to do it? 

Since I think this is a trivial change and seems very useful, it should be in the new version in a day or two.

Also, cross-referencing nodes but not properties on a CQUAD4 is not an option for this version (e.g. so you can get area, but not mass).

**Comment by Ravi2015** [comment]
Thanks so much for your quick response and detailed explanations Steve...really appreciate it :+1: 

Looking forward to the release of v0.7!
