### ISSUE TITLE
NodeID To Element IDs Map issue

### ISSUE THREAD

**Issue by Ravi2015** [SteveDoyle2/pyNastran#195]
Hello,

I'm using pyNastran v0.6.1.

There seems to be an issue with getNodeIDToElementIDsMap() BDF method.

It is not returning the RBE2 elements attached to a node. 

I'm trying to identify if a particular RBE2/ CBUSH element is a 'free' ended  element, i.e. one of its nodes is unconnected to any other element (normal element or rigid one). Now, some of the elements have a node connected to another RBE2 element, but because the getNodeIDToElementIDsMap method is not returning this RBE2 element, it's mistakenly identifying this node as a free end and the corresponding element as a free-ended element :(

Is there any fix/ workaround? Also, what other type of elements are missed out by getNodeIDToElementIDsMap method other than RBE2?

I tried to write a small function myself that goes through the model.rigidElements list and checks if a given node id is in one of the elements' node IDs (element.nodeIDs()), but for RBE2 type elements, there seems to be no attribute called nodeIDs like the normal elements.

So, I guess I have to do the check by using element.gn, element.Gmi, etc. for RBE2 type elements, something else for RBE3 type elements, etc. for the various element types in model.rigidElements

Thanks & regards!

**Comment by SteveDoyle2** [comment]
RBExs are not included in the "self.elements" group, so it won't work
with getNodeIDToElementIDsMap.
CMASSx, CONM2s, and MPCs, and thermal elements (e.g. CHBDY, CONV) will also
not be found.  The method is meant for things with clear "self.nodes" that
have stiffness matrices (as opposed to constraint equations).  Something
like an MPC to me is a constraint (n1.x+n2.x=n3.x) and since an RBEx is
implemented using MPCs, in some sense it's more like a constraint than an
element.

> Is there any fix/ workaround?  So, I guess I have to do the check by
using element.gn, element.Gmi, etc. for RBE2 type elements, something else
for RBE3 type elements, etc. for the various element types in
model.rigidElements

Yes.  There is no nodeIDs method because it operates on a master/slave
nodes paradigm.  So there could be a master/slave nodes function, but I'm
hesitant to add a nodeIDs method.

**Comment by Ravi2015** [comment]
Ok..got it. Thanks again for the clarifications!

**Comment by SteveDoyle2** [comment]
correction...thermal elements like CONV and CHBDYx are included in the list of "elements".  That may be the wrong choice though.
