### ISSUE TITLE
nastran_to_stl does not apply thickness

### ISSUE THREAD

**Issue by vetereb** [SteveDoyle2/pyNastran#210]
The nastran_to_stl function does not apply thickness.  This results in an unprintable STL file.

**Comment by SteveDoyle2** [comment]
As far as I knew, STLs did not have a thickness.  Can you send me a small ASCII and binary example that has thickness?

**Comment by vetereb** [comment]
In a sense, that is true but in the case of converting nastran to STL a CQUAD or otherwise should have a thickness when expressed as geometry in the STL format.  This means that to properly specify a CQUAD in STL form would take 12 triangles.  Not the two currently done.  In addition the two triangles specified are on the mid plane of the plate, not the true surface.

I don't have an example readily available but I can create one.

**Comment by SteveDoyle2** [comment]
I don't think that's the way you want to do it.  Nodes are defined
typically at the midplane so if you're projecting nodes outwards, you're
not going to have a closed model because there will be V shaped gaps in the
solid model.  Is there a reason you want to make a 3D print with thickness
other than to just save on material?  I think you'd run into major issues
with model stability.

I think a much better option is to just extrude the thickness, create
CHEXAs, skin those back to CQUAD4s, and export that.

**Comment by vetereb** [comment]
I'm not entirely following you.  CHEXAs are not processed in nastran_to_stl as is.  I'm not sure how this is a viable path forward.  Or are you suggesting that adding CHEXA processing would be better than using the PSHELL information to apply thickness?  Though I would still not fully grasp how this path would work.  I'll give this more thought.

As far as why, for any 3D print to be useful it should reflect the actual properties of the model.  If you picture a modeling a table the thickness of the table surface as-is is determined by the printer resolution.  It will (depending on printer) just apply the minimum about of material possible.

On the V shaped gaps, I believe that you're making an assumption of using all the nodes as-is in STL creation (otherwise I'm not sure what causes these to arise).  I don't propose doing that.

**Comment by SteveDoyle2** [comment]
> I'm not entirely following you. CHEXAs are not processed in nastran_to_stl as is.

It could be a new feature or you can just do the conversion yourself.

> Or are you suggesting that adding CHEXA processing would be better than using the PSHELL information to apply thickness? 

Yes.  PSHELLs are 2D and have 2D assumptions built into the formulation (e.g. if two elements connect at the midplane they connect at the far planes as well; PCOMPs don't even satisfy the continuity equation within themselves).

> On the V shaped gaps, I believe that you're making an assumption of using all the nodes as-is in STL creation (otherwise I'm not sure what causes these to arise). I don't propose doing that.

Unless the normal is identical between neighboring quads, you will introduce gaps when you project the normal outwards despite having common nodes and/or common thicknesses (even if you use the elemental thicknesses instead of PSHELL-based thickness).  You have additional information about your problem (e.g. it's good enough to equivalence the nodes), but it's technically wrong.  You would also have even more issues as the thickness changes along the model if you're using a PSHELL to set properties instead of elemental thicknesses.

If that's not what you're proposing, then I'm not clear on what it is you are proposing.

> If you picture a modeling a table the thickness of the table surface as-is is determined by the printer resolution. It will (depending on printer) just apply the minimum about of material possible.

I'm not following.  A simple table can be well represented by an OML.
