### ISSUE TITLE
PARAM,OMID,YES when reading an op2 file

### ISSUE THREAD

**Issue by saullocastro** [SteveDoyle2/pyNastran#220]
Dear Steve, does pyNastran support PARAM,OMID,YES when reading an `op2` file?

If not, is there an interest to implement this?

Regards
Saullo

**Comment by vlxm** [comment]
Hi,
I believe PARAM,OMID,YES does not change the coordinate system in which stress, strain and forces are expressed in the op2.
Regards.

**Comment by saullocastro** [comment]
Indeed, you are right. But since the post processors would transform the
op2 output when identifying OMID=TRUE, we could think of pyNastran doing it
as well.

**Comment by SteveDoyle2** [comment]
I agree, it should be on the result object (e.g. CPlateStress/Strain/Force), but because it's not in the OP2, it would need to be calculated with a function similar to:

    def get_data_in_material_coord(self, bdf, eids=None):  # eids=None -> all eids
        return data

OP2s may or may not have the geometry contained within them depending on the flags the user sets in the BDF.  Considering the OP2 geometry reader is not the greatest and just creates BDF data members anyways, I'd just use the BDF to be safe.  If the OP2 ever supports geometry properly, instead of passing in the BDF object, you could just pass in self.

CQUAD4s/CTRIA3s seem easy enough, but solid elements will probably be harder.  What's also strange is solid elements have a coordinate system, which is weird since they don't consider OMID.

@saullocastro, can you write the functions?

**Comment by saullocastro** [comment]
@SteveDoyle2 yes I can.

I will start with stress transformation for 2D elements first. Thank you!

**Comment by SteveDoyle2** [comment]
There's a flag on the stress code that I believe is the material coord flag.  Strangely, the stress/strain/force is not stored in that form, but it still might be of use.

**Comment by saullocastro** [comment]
I would suggest closing this issue with pull request  #310
