### ISSUE TITLE
MSC Nastran 2016, HDF5, reader for PyNastran

### ISSUE THREAD

**Issue by saullocastro** [SteveDoyle2/pyNastran#308]
MSC Nastran 2016 started using the HDF5 format as a new output option (Nastran saves it as a `.h5` file)

I tested it and it is very straightforward to implement a `.h5` reader using PYTables (http://www.pytables.org/index.html).

For example, to read the output of a node diplacement one should do something like:

```
import tables

h5 = tables.open_file('nastran_output.h5')
h5.NASTRAN.RESULT.NODAL.DISPLACEMENT[0]
```

to get something like:

```
[nodeid, [T1, T2, T3, R1, R2, R3], subcase index]
```

I am suggesting this as a new line of development in PyNastran. What do you guys think?

**Comment by SteveDoyle2** [comment]
I'm fine with it as long as it works with what's already there.  I don't have MSC Nastran 2016, so I can't really develop it though.

**Comment by saullocastro** [comment]
Hi @SteveDoyle2. I agree with you. These last weeks I've been playing with PyNastran v 0.8 and it is amazing the speedup you guys achieved reading the op2 file. This kind of makes less important this issue I proposed, but I am willing to work on the HDF5 reader in a near future.

For now, due to my current needs, it is more likely that I work on Issue #220 first.

**Comment by SteveDoyle2** [comment]
closing due to innactivity & lack of need

**Comment by mjredmond** [comment]
FYI, I have a simple python library at mjredmond/mrNastran that handles a partially compatible Nastran h5 format.  I don't know the full spec, so I was guessing in places.  It also converts punch results files to h5 format.  I'd like to use pyNastran instead of my own bdf reader.  Does anyone have the full Nastran h5 format spec?  That would be pretty useful.

**Comment by SteveDoyle2** [comment]
I've thought about writing an OP2 to hdf5 reader, so you basically swap out
the numpy arrays for hdf5 arrays.  It would definitely help for those 60 GB
OP2 files.

There would be a flag to maintain compatibility.  I have no idea about the
spec though. Could you put something together, even if it's partial?

Cutrently the op2 reader can export to hdf5.  It follows the internal
structure rather than the spec, so I'm sure that could be improved.

**Comment by mjredmond** [comment]
I've got some basic stuff at https://github.com/mjredmond/mrNastran.  I'll be refactoring it a bit, but the basic premise is there.  I have a punch reader that works pretty well for reading results.  It's pretty slow though... a 60 GB punch file takes about 3 hours to convert, but you only need to do it once.  The pynastran op2 reader could export results in a compatible format, so minimal coding would be needed to add support for op2 conversion.
The main thing I need to do is refactor to use pynastran as the bdf reader.

**Comment by mjredmond** [comment]
I renamed the repo to [.](https://github.com/mjredmond/h5Nastran)  It should have enough bdf and punch table support for you to take it for a test drive.  Please let me know what you think.  Ultimately I think it would be a good idea to add it as a builtin feature to pyNastran, maybe as a submodule.  What do you think?  Also, I'd like to reopen this issue so the discussion can be more visible to others.  Thanks.

**Comment by SteveDoyle2** [comment]
Your module is very cool.  I'm very interested to see how our packages can work together.

I'm not sure about the best way to interface (e.g., a separate package or just a single one), but that's solvable.  I guess backing up a little, as is, there is:
  1. BDF and OP2 capability that is standalone
  2. examples
  3. some converters that I find useful (e.g., STL to BDF)
  4. a GUI capability that requires the previous three and implements it's own vectorized BDF reader (which would be better using your package).

So if pyNastran was split, it's could be 1/2 or 1/2/3.  If it's 1 or 1/2, that might be annoying to install.  I'd also like to avoid circular dependencies between our packages, so either we just merge them or split up pyNastran.  Thoughts?

Regarding using your package, I guess my first question is do you have some examples?  I'm tried to figure out how to use it (e.g., read a BDF, get the XYZs from the nodes, modify them and write the new deck).

Also, I saw you have a BDF_LINES entry.  Is that supposed to be the full deck or just the unparsed data?  Is that updated when you modify data and write it back out?

**Comment by mjredmond** [comment]
I'm fine with merging as long as I can still have push rights to the h5Nastran part.

I updated the example and added an example model.  To modify the bdf you'd get the pynastran bdf instance (db.bdf) and modify that, rewrite the bdf, and create a new h5 database.  My intensions for the h5 database is for it to be a post-processing tool, although I guess you could use the structure for a vectorized bdf.

The BDF_LINES entry is the entire bdf file written out by pynastran.  Currently, when you do
db.load_bdf() with no filename, it will create the pynastran bdf from that.  The goal is to have h5Nastran recreate the bdf from the h5 data.

**Comment by SteveDoyle2** [comment]
> I'm fine with merging as long as I can still have push rights to the h5Nastran part.

You now do :)

>  My intensions for the h5 database is for it to be a post-processing tool

I agree with that.  My first thought was definitely to use it for the GUI.  It's an easier problem and you can build up the code for things like coordinate transforms.

I do occasionally get in to the 4 million solid element range and the BDF class sort of falls apart.  HDF5 would be really nice there.

This is definitely cool though.  I'm impressed.  You did this very quickly and it's good.  

I'm still very much trying to figure it out though.  I use an old MSC Nastran and a current NX, which doesn't have HDF5, so I have no idea what a domain is (maybe it's a superelement?).  I do know the answer to one of your TODOs though.  SOUT is an integer for the PCOMP.  0 means NO and 1 means YES.  If you're looking at the QRG, the order that they list the options is the order that the integers go starting from 0.

**Comment by mjredmond** [comment]
Thanks!  Where do you want to put h5Nastran?  You probably know better than I where is best.  And thanks for the help with the SOUT.  I wish they would just store the same info as what is actually in the bdf... oh well.

**Comment by SteveDoyle2** [comment]
Good question...I'm not sure.

Currently, the only "finished" module like that is the OP2 vs. OP2Geom
classes.  Those are just in pyNastran/op2.  I figured it was clear enough
given the names are close.

H5Nastran is organized a bit differently and I think because it's trying to
follow MSC's naming convention.  That's a good thing once you understand
that, but it's unclear to someone sifting through the package looking for
the bdf reader.  It also might get a bit messy if we merge the directories
too closely, so maybe it's better to make it, pyNastran/bdf_h5 (or
bdf_hdf5/h5bdf) that sits at the root level.  Then maybe break out the PCH
reader into a pyNastran/pch (pyNastran/pch_h5/pch_hdf5/h5pch) directory.
The other thing that's a little different is there isn't currently anything
(other than the GUI) that manages both the BDF and OP2/PCH.


The alternative is to put it at the root level as more of a standalone
package, so just pyNastran/h5Nastran.

I think I don't really have a huge preference other than I'd like to help
it to get some exposure, so if it's sitting buried in some folder, it
won't.  I think it's up to you how you want to organize it.  I do know how
to speed up the BDF card reading a bit though, so hopefully you don't mind
my help too :)

**Comment by mjredmond** [comment]
I like it under pyNastran/h5Nastran for now.  Simpler is better, and it would get more exposure as you mentioned.  It can evolve if and as needed.  I always welcome help, so feel free to make additions/improvements.  Thanks.
