### ISSUE TITLE
op2/data_in_material_coord.py does not take the correct THETA

### ISSUE THREAD

**Issue by saullocastro** [SteveDoyle2/pyNastran#312]
After testing with more generic models I realized that 

https://github.com/SteveDoyle2/pyNastran/blob/master/pyNastran/op2/data_in_material_coord.py

does not take the correct `THETA` ([see this line](https://github.com/SteveDoyle2/pyNastran/blob/master/pyNastran/op2/data_in_material_coord.py#L127)). Now I am applying a patch to calculate the corrected theta as:

`THETA_corr = THETA + beta - alpha`, where `alpha` and `beta` are obtained from the CQUAD4 figure in Nastran's Quick Reference Guide.

I noticed that the correction will be necessary only for CQUAD elements.

**Comment by SteveDoyle2** [comment]
It's also important to consider thetaMCID as an integer (the X axis is projected onto the plane of the element), a float (what's currently done), and as None (stress in element coordinate system = stress in material coordinate system).

**Comment by saullocastro** [comment]
Fully agree @SteveDoyle2. Soon there will be a pull request comming up.

**Comment by SteveDoyle2** [comment]
The CQUAD4() material_coordinate_system() function might help.  It's half implemented (only supports thetaMCID as an integer and only for CQUAD4s, but I use it to plot a reduced set of material coordinate systems (e.g. a full XY coordinate system per region instead of just the material X axis on each element).

see https://github.com/SteveDoyle2/pyNastran/blob/master/pyNastran/bdf/cards/elements/shell.py#L1613

**Comment by saullocastro** [comment]
@SteveDoyle2 I think you can close this issue
