### ISSUE TITLE
pyNastran from MATLAB

### ISSUE THREAD

**Issue by alby3z** [SteveDoyle2/pyNastran#325]
I am using pyNastran from MATLAB, I've noticed that pyNastran 0.7.2 works, whereas pyNastran 0.8 does not. (Both versions works fine using Anaconda spyder)

Are there any differences (in the setup.py process) that could hide the pyNastran installation to other softwares?

**Comment by SteveDoyle2** [comment]
No idea.  I'm not familiar with calling Python from Matlab.  Maybe `python setup.py develop` vs. `python setup.py install` has something to do with it?  

Also, would you mind sharing your script?  I'm curious to how you're using it and I'm sure other people are as well.

**Comment by alby3z** [comment]
I've found a workaround for the problem in MATLAB. For some reason the file `__init__.py` (in the pyNastran folder located in the site-packages folder of the Python installation) of the version 0.8 caused MATLAB to not successfully import the module. _NB: The problem relies on how MATLAB loads the Python modules, a full understanding of this issue requires me to contact Mathworks support. I will do this in the next week._

I've simply commented a part of that file (using the relevant `__init__.py` of pyNastran 0.7.2 as layout) and at that point MATLAB was able to import the module.

The modified file is attached below:

[__init__.py.txt](https://github.com/SteveDoyle2/pyNastran/files/373655/__init__.py.txt)

For what concerns a MATLAB script I will prepare a simple .m file that I'll share in a few days.

**Comment by SteveDoyle2** [comment]
What is the output of `hasattr(sys, '_MEIPASS')` when calling from Python?  

It's a pyInstaller specific variable that pyNastran uses to indicate if you're running an exe of the GUI or not.  When building the GUI, the `__version__.py` file is created.  Otherwise, the code looks for your git revision.  If it cannot find it, it just returns a message saying it doesn't know (e.g. you installed the master from a zip file).

What I think is happening is MATLAB bundles python using pyInstalller and therefore the variable is defined when it shouldn't be.

**Comment by alby3z** [comment]
Calling Python module in MATLAB is possible, but not all the commands are available.
For example I can access to an attributes of a class, but I can't always use a class as an input of a function (I'm not a programmer so I could misinterpret something).

For example the following command is callable in MATLAB:

```
>>import py.pyNastran.bdf.bdf.BDF %equivalent to Python command: "from pyNastran.bdf.bdf import BDF"

py.hasattr(py.pyNastran.bdf.bdf.BDF,'_MEIPASS') %equivalent to Python: "hasattr(BDF,'_MEIPASS')"

>> 0
```
 It gives 0 that in MATLAB is equivalent to boolean False.

Whereas the command:

```
>> py.hasattr(py.sys,'_MEIPASS')

Undefined variable "py" or class "py.sys".
```

gives an error.
On the other hand I can call:

```
>> py.sys.api_version

ans = 

  Python int with properties:

    denominator: [1x1 py.int]
           imag: [1x1 py.int]
      numerator: [1x1 py.int]
           real: [1x1 py.int]

    1013
```

with no problem.

**Comment by SteveDoyle2** [comment]
I think that kinda makes sense.  In your example, `BDF` is a class, while `sys` is a module/file.  I think the solution is just to not access magic variables from modules.

The GUI exe requires a magic pyInstaller variable (`sys._MEIPASS`) to work, so I think the fix is to dynamically make an `is_pynastrangui_exe = True` flag and just set it to `False` by default.  It already dynamically makes an `__version__` file, so why not one more...

**Comment by SteveDoyle2** [comment]
This should be fixed now.  Give it a shot and let me know.

**Comment by SteveDoyle2** [comment]
closed due to inactivity and I think it's fixed
