### ISSUE TITLE
Op2FileFormat

### ISSUE THREAD

**Issue by 461353349** [SteveDoyle2/pyNastran#344]
@SteveDoyle2 
Can you send me the file about Op2 FileFormat, I want to study the parser, thanks a lot. 
Email: 461353349@qq.com

**Comment by SteveDoyle2** [comment]
You can find information about the OP2 in MSC's DMAP guide.  The first 1/3 is all about the OP2.    https://simcompanion.mscsoftware.com/infocenter/index?page=content&id=DOC10965&actp=RSS

The challenge with the OP2 is it's a Fortran formatted file, which is excessively complex.  Blocks will be split if it goes over 2^16=65536 bytes (16384 int/float values), which for a displacement table means you get a split every 2048 nodes.  There are all sorts of codes to define various states, so you just need to process those states properly (e.g. a CTRIA3 is element type 74, a centroidal CQUAD4 is 33, a 5-noded CQUAD4 is 144; the scode flag flips between stress and strain results).

There's a lot of Python black magic in the code regarding passing data around to the result objects in order to reduce the duplication of classes (e.g. a displacement result and a spc force result are the same object with a different header; a real displacement result and a eigenvector result are almost the same well).

Additionally, a lot of work went into the flow of the program to properly size data objects and convert bytes quickly into ints/floats.  Fortran byte ordering is different than Python/C/Matlab/everybody else, so it's a challenge to rapidly read data when the types are changing.  Turns out it's way faster to just cast the data twice (to ints and floats) vs. doing it correctly once.  That's why it can read a 2 GB file in 4 seconds.  That's right at the limits of file read speed, so writing it in a complied language wouldn't really make it faster.

Beyond that (and obviously the code) I do not have documentation.  There are lots of edge cases that a file parser needs to handle (e.g. how does optimization work, what about xyplots, what about when the incorrect data).  That's why I throw ~12,000 examples at the code.

I guess I'm not totally sure on what your goals are.  The OP2 is a structured format (unlike the F06), but is mind numbingly complex and is also inconsistent (and that's before you try to support reading NX/Radioss OP2s), so it's a challenge to implement.  My best guess is you want to use the OP2 reader in another language.  If you're after Matlab, you can already do that.

**Comment by 461353349** [comment]
I want the OP2 reader in C++.  Wrapping python in C++ is a way, but I donnot have an effective method to pass the big data from Python to C++.
I have scanned the 'DMAP Programmer’s Guide', But I have still no a clear clue. For example, ANSYS Help has the detailed description about result file format as follows:
https://www.sharcnet.ca/Software/Ansys/16.2.3/en-us/help/ans_prog/Hlp_P_INT1.html

**Comment by SteveDoyle2** [comment]
Nastran doesn't have documentation that's that nice.  I don't work for MSC/NX so...yes, I agree.  The OP2 is a decently described format once you know what to look for, but diving into it is a bit cryptic.  I'm not up on my Fortran, but I'm sure that would be a big help when reading the manual.  I just blindly started parsing a small example, just trying to skip everything, and building up from there.  It took me a while before the manual even helped.

You have a few options:

1.  Parse the F06.  It's slow because it's not binary.  It's a nightmare to parse for more complicated cases, but you should be able to get multi-subcase transient results working fairly easily.  It'll fall apart when you want to use superelements, optimization, or have poorly defined case control decks.  Also, tables for static, transient, and frequency results often cannot be handled with the same parser.  That's the real reason I gave up F06 parsing.

2.  Parse the PCH.  It's also slow, but will be much faster and easier to parse than the F06.  I've done transient parsing of it for a single subcase, but never even looked at one for optimization or superelements.

3.  Do a batch call and write a CSV/your own custom binary file/HDF5 file.  It's a lot easier than the first 2 options and could be just as fast.

4.  Wrap your C++ code using SWIG and pass the data directly to C++.  You start running into 64 bit problems though.  It's supposedly more than a little hard to build 64-bit Python/SWIG executable.  That said, I use 64-bit libraries written in C++, so I don't understand the issue.

5.  We could write a OP2 reader in C++ and open source it.  I'm ok enough with C++ to do simple math/fix bugs, but I've never read a binary file, never messed around with memory allocation, don't really understand pointers, and don't know how to build code outside of calling a make file or a simple gcc call.

**Comment by 461353349** [comment]
Thanks SteveDoyle2 very much.
3.th, 4.th and 5.th are good methods.     
5.th will need more time, But the result will be more attractive. Opening source is also an honour.  Maybe your python code would be important reference. I am not sure when I have time to do it.
Qt or boost will simplify the memory allocation and destruction, Reference count is introduced as python. Getting Start with Qt wouldnot be difficult.

**Comment by SteveDoyle2** [comment]
Nastran doesn't have documentation that's that nice.  The OP2 is a decently
described format once you know what to look for, but diving into it is a
bit cryptic.  I'm not up on my Fortran, but I'm sure that would be a big
help when reading the manual.  I just blindly started parsing a small
example, just trying to skip everything, and building up from there.

You have a few options:

1.  Parse the F06.  It's slow because it's not binary.  It's a nightmare to
parse for more complicated cases, but you should be able to get
multi-subcase transient results working fairly easily.  It'll fall apart
when you want to use superelements, optimization, or have poorly defined
case control decks.  Also, tables for static, transient, and frequency
results often cannot be handled with the same parser.  That's the real
reason I gave up F06 parsing.

2.  Parse the PCH.  It's also slow, but will be much faster and easier to
parse than the F06.  I've done transient parsing of it for a single
subcase, but never even looked at one for optimization or superelements.

3.  Do a batch call and write a CSV/your own custom binary file/HDF5 file.
It's a lot easier than the first 2 options and could be just as fast.

4.  Wrap your C++ code using SWIG and pass the data directly to C++.  You
start running into 64 bit problems though.  It's supposedly more than a
little hard to build 64-bit Python/SWIG executable.  That said, I use
64-bit libraries written in C++, so I don't understand the issue.

5.  We could write a OP2 reader in C++ and open source it.  I'm ok enough
with C++ to do simple math/fix bugs, but I've never read a binary file,
never messed around with memory allocation, don't really understand
pointers, and don't know how to build code outside of calling a make file
or a simple gcc call.

**Comment by SteveDoyle2** [comment]
closing due to inacctivity
