### ISSUE TITLE
OP2 readers doesn't work, when I try to read an op2 file which is created by nastran2012.2

### ISSUE THREAD

**Issue by b1a2b3c4d** [SteveDoyle2/pyNastran#388]
I receive the following error message：
`  Traceback (most recent call last):
  File "\pyNastran\gui\gui_common.py", line 3013, in on_load_results
    load_function(out_filenamei, self.last_dir)

  File "\pyNastran\converters\nastran\nastranIOv.py", line 3979, in load_nastran_results
    model.read_op2(op2_filename, combine=False)

  File "\pyNastran\op2\op2.py", line 483, in read_op2
    OP2_Scalar.read_op2(self, op2_filename=op2_filename)

  File "\pyNastran\op2\op2_scalar.py", line 1516, in read_op2
    table_names = self._read_tables(table_name)

  File "\pyNastran\op2\op2_scalar.py", line 1626, in _read_tables
    self._read_results_table()

  File "\pyNastran\op2\op2_scalar.py", line 2716, in _read_results_table
    self._read_subtables()

  File "\pyNastran\op2\fortran_format.py", line 367, in _read_subtables
    self._read_subtable_3_4(table3_parser, table4_parser, passer)

  File "t\pyNastran\op2\fortran_format.py", line 418, in _read_subtable_3_4
    n = self._read_subtable_results(table4_parser, record_len)

  File "\pyNastran\op2\fortran_format.py", line 539, in _read_subtable_results
    n = table4_parser(data, ndata)

  File "C:\Users\Xu\Desktop\pycharmproject\pyNastran\op2\tables\oug\oug.py", line 310, in _read_oug_4
    n = self._read_oug_displacement(data, ndata, is_cid=False)

  File "\pyNastran\op2\tables\oug\oug.py", line 396, in _read_oug_displacement
    assert self.table_name in [b'BOUGV1', b'ROUGV1', b'ROUGV2', b'OUGV1', b'OUGV2'], self.table_name
AssertionError: OUG1`
PyNastran version is v 0.9. In addition could you tell me where is the doc introducing the structure of op2？

**Comment by SteveDoyle2** [comment]
The documentation for the OP2 format is provided by MSC/NX.  It doesn't really matter, whose DMAP guide you use, or which version, as it's about the same.  They both leave things out, so you're best off referencing both and the latest version you have.  I don't have an NX guide handy.  MSC's is easier to come by:

https://simcompanion.mscsoftware.com/infocenter/index?page=content&id=DOC11149&cat=MSC_NASTRAN_DOCUMENTATION_2017&actp=LIST

Regarding details of the OP2 format in pyNastran's documentation, it's excessively complicated and not worth the 20 pages of over-simplified explanation to explain something that you don't probably even want to know.  You're welcome to read the code though.

The error you have is due to the code being strict about what it reads.  It's necessary to catch bugs.  I test against the entire nast and tpl directories in MSC 2005.1 and NX 10.  There are a few other models that I run as well.  

I need an example of the crash to fix it.

**Comment by b1a2b3c4d** [comment]
[Here is the files.](https://drive.google.com/drive/folders/0BxaMFoAUrxpBbWlpRTM5NjNLN3M?usp=sharing)

**Comment by SteveDoyle2** [comment]
That bug is fixed.  However, MSC 2012 outputs different tables than MSC 2005 and I expect another unsupported table.  Can you an example with:

VELOCITY(SORT1,REAL)=ALL

**Comment by b1a2b3c4d** [comment]
Sorry I didn't have the unsupported table which you mentioned. Thank you for fixing the  OUG1 bug.

**Comment by SteveDoyle2** [comment]
Awesome!  Thanks!
