### ISSUE TITLE
Implement export filter for op2 -> hdf5 format

### ISSUE THREAD

**Issue by murmlgrmpf** [SteveDoyle2/pyNastran#411]
Hello,

I am trying to get results of a MSC Nastran op2 file into Matlab for postprocessing. The direct import of the op2 object failed on me, even the workaround in the manual did not work.
Now I wanted to have a try on exporting the OP2 object to HDF5. Do you have a starting point on where to look in order to implement an hdf5 export filter?

Best,
Thomas

**Comment by SteveDoyle2** [comment]
No, there is no HDF5 exporter.  I know it's been done (and was very fast/good), but it wasn't done by me, so I don't have the code.  It's probably not a ton of work to do in a very general way (at least for the OP2, not the BDF attributes that can come in from the OP2Geom class).

The problem is I'm just not very familiar with HDF5.  If you have a prototype for say the displacement that would go a long way to getting that in there for every object.

**Comment by murmlgrmpf** [comment]
Thanks for the info! I figured out, that msc nastran can output hdf5
directly now. But I still have to figure out, whether it is possible to get
the system matrices/ arbitrary data blocks in there as well. If it doesn't
work and I have to fall back on op2, chances are, I would end up writing an
hdf5 export for pynastran instead of an op2 import for matlab (matlab has
hdf5 support) ;-)

Does the op2 or pch parser of pynastran support arbitrary datablocks?


SteveDoyle2 <notifications@github.com> schrieb am Do., 24. Aug. 2017 um
18:32 Uhr:

**Comment by SteveDoyle2** [comment]
Turns out hdf5 is actually way easier than I thought, so I went ahead and
(almost) globally implemented it in about 100 lines. Currently, I think
only eigenvalues are missing.   There is a
`model.export_to_hdf5(hdf5_filename)` now.  Doesn't matter so much since
MSC supports it, but I'd bet NX, Autodesk, and Radioss don't.

Regarding arbitrary data blocks, I'm going to say no since I don't know
what those are.  PyNastran reads almost every table that I kbow about.  The
philosophy is to just add what isn't supported as opposed to making the
user do that, though they can do that too.

**Comment by murmlgrmpf** [comment]
Thanks a lot! I couldn't find the new hdf5 export on Master. However now I import sparse binary op4 files and save the matrices to matlab files by scipy.io.
I'm still testing it, but it seems to be working like a charm! Keep up the good work!

**Comment by SteveDoyle2** [comment]
Thanks!  Glad you like it!
