### ISSUE TITLE
PyNastranGUI.exe crashes with DLL error when loading *.nas file

### ISSUE THREAD

**Issue by libakdk** [SteveDoyle2/pyNastran#429]
Hi there

PyNastranGUI.exe exits when loading NAS geometry file - pls find file attached

btw - I downloaded the v1.0, but Help>About says v0.9.0+dev.eaf06e1

[geometry.zip](https://github.com/SteveDoyle2/pyNastran/files/1372141/geometry.zip)

[geometry[rename txt to nas].txt](https://github.com/SteveDoyle2/pyNastran/files/1372136/geometry.rename.txt.to.nas.txt)

**Comment by SteveDoyle2** [comment]
The v0.9.0+dev.eaf06e1 is just an outdated note.  It really is v1.0.

It looks like there's a DLL error.  I'm on a different system (that's also been updated since I built the exe, but it used to work), but I'm getting:

    Intel MKL FATAL ERROR: Cannot load mkl_avx2.dll or mkl_def.dll

That occurs after the gui launches and right after opening a file or just calling:
    pyNastranGUI.exe geometry.bdf

I really need a VM to test the gui on, but that's harder to get than it should be.


I guess I'd suggest checking out the latest v1.0-dev branch and running that.  It takes installing python & vtk, but with Anaconda, it's pretty easy.
