### ISSUE TITLE
Question on NASTRAN Substitution Variables

### ISSUE THREAD

**Issue by PabloBeranger** [SteveDoyle2/pyNastran#433]
It is possible that the variables of substitutions are taken into account during the reading of a bdf.
You can see "Symbolic Substitution" in the NASTRAN Quick Reference Guide or in the Installation and Operations Guide.
The principe, i thing, will be similar like OpenMDAO variables.

Thanks

**Comment by SteveDoyle2** [comment]
That's funny.  Of course there's another Nastran syntax form.

I thought that was only an OpenMDAO's thing, but yes (at least at a cursory
glance) it is supported (or close to it) with some restrictions.  Some are:
 - put a %word instead of %word%
 - the example in the QRG I see has a thickness value which is 9 characters
(not a max of 7)
 - it looks like they define the variable in the system section
 - no case control support

See:

    def set_dynamic_syntax(self, dict_of_vars):
        """
        Uses the OpenMDAO syntax of %varName in an embedded BDF to
        update the values for an optimization study.

        Parameters
        ----------
        dict_of_vars : dict[str] = int/float/str
            dictionary of 7 character variable names to map.

        .. code-block:: python

          GRID, 1, %xVar, %yVar, %zVar

          >>> dict_of_vars = {'xVar': 1.0, 'yVar', 2.0, 'zVar':3.0}
          >>> bdf = BDF()
          >>> bdf.set_dynamic_syntax(dict_of_vars)
          >>> bdf.read_bdf(bdf_filename, xref=True)

        .. note:: Case sensitivity is supported.
        .. note:: Variables should be 7 characters or less to fit in an
          8-character field.

        .. warning:: Type matters!
        """

**Comment by PabloBeranger** [comment]
During the tests that I realized, I used the openMDAO format %xxxxxx, but I have to remove the limit of 7 characters in the code. Of the function "set_dynamic_syntax" because my variables names have more than 7 characters. The NASTRAN variables of subsititions which can have 32 characters maximun.
But I am not certain that it will work in every case.

I use most of the time the free ormat.
