### ISSUE TITLE
Question on the encoding

### ISSUE THREAD

**Issue by PabloBeranger** [SteveDoyle2/pyNastran#434]
Hello,

I have files which are encoded in ANSI with character CR-LF at the end of line.
When I want to read them with pyNastran with the encoding option ='latin1' I have an error of encoding.

What is the method to employed for not have encoding errors ?

**Comment by SteveDoyle2** [comment]
Encodings can be tricky..  Turns out, (this is news to me too), ANSI is not an encoding. It typically means one of the following:

-ISO 8859-1 (latin1 i think...)
-Windows CP1252
-Current system encoding on a Windows machine (in Win32 API terminology).

See https://stackoverflow.com/questions/701882/what-is-ansi-format

I think you just use cp1252,  if not thankfully there are only 91 encodings in python 2.7...

**Comment by SteveDoyle2** [comment]
The full list of encodings in Python 2.7

https://docs.python.org/2/library/codecs.html#standard-encodings

**Comment by SteveDoyle2** [comment]
I think this was solved; closing
