### ISSUE TITLE
QUESTION: regarding subcase deepcopy for SET objects

### ISSUE THREAD

**Issue by mjredmond** [SteveDoyle2/pyNastran#442]
I was looking into this issue a little more, and it seems that the biggest slow down is due to deepcopying of large SET objects.  It makes sense to me that there should be only one instance of a given SET object, since in the BDF the same SET objects are reused for each subcase.  Would it be acceptable to not deepcopy the SET object when deepcopying the subcase?  This increases bdf read speed a ton.  This was one of the major drawbacks for me in using pyNastran (too slow reading the bdf), since my bdf's have large SET objects.  I've typically resorted to my own python scripts, but I'd prefer to use and contribute to pyNastran in the future.

Also, is there a way to access the SET objects besides through the subcases?  I don't think I've seen anything.  That might be a useful feature.

Thanks!

**Comment by SteveDoyle2** [comment]
You'd probably also need to rewrite the `.keys()`,  `.iterkeys()`, etc. methods as well.

**Comment by mjredmond** [comment]
I forgot SET cards worked like that...
What happens if there's a another subcase that uses SET 100

SUBCASE 4
     DISP = 100

Will this use the first or second definition?  If it uses the second, then a simple solution would be to just use the last definition created and keep a list of the SET cards in a dict and append as new definitions are created (I'm not sure how they're currently stored when reading the bdf).

example:
dict_of_lists = { 100: [ [100,], [100, 101] ], ... + other SET cards }

Thanks.

**Comment by SteveDoyle2** [comment]
It uses the global SET card, so `SET 100 = 100`.

There is probably also an error currently where the user loads in the model above and changes the SET 100 card globally.  It's thankfully rare.  So I think it probably needs to use the new approach anyways.

Regarding the examples, I'd just do `subcase1['SET 1'][0] + subcase1['SET 2'][0]`, where `subcase1['SET 2']` is a list that is the `values, options` for the card and `options` is just an empty list for the SET cards.

I guess as long as there aren't multiple `SET 100` cards, I wouldn't be opposed to a simpler method to access the data.  That could just be thrown by the method, maybe something like:

    def case_control_sets(set_ids, subcase=None):
        # subcase = None -> look globally, but prevent duplicate SET 100 cards
        # subcase = 10 -> just get subcase 10
        # subcase = [10, 11] -> consider 10 and 11 (prevent duplicate SET 100 cards again)
        return ids

**Comment by mjredmond** [comment]
I tested your example at the top and SUBCASE 3 is valid.

Where would the case_control_sets method be implemented?

Looking through case_control_deck.py, subcase.py, and bdf_interface/subcase_card.py... I'm leaning towards refactoring a bit of code to simplify things.  Would that be ok with you?  If so, what would be required accept the pull request... maintaining the current api and passing the current tests?  Is there any other work being done in those files right now that would affect anything?  If you're ok with refactoring, I can come up with an initial proposal without the implementations and show it to you before I start working on it.  I'm fairly busy right now between work and home, but I can squeeze some time in if you're on board.  Also, if you have any additional concerns with how things currently work I can try to address those issues as well.

I'm not too familiar with the code base right now, but I can get the hang of it.

Thanks.

**Comment by SteveDoyle2** [comment]
> I'm leaning towards refactoring a bit of code to simplify things.

That's fine.  It's kind of a mess.

You probably should know about the new approach.  As is the Case Control doesn't do any validation (e.g., `DISP(junk) = ALL`)  is totally fine.  Not so bad for that, but for other cards, it's a bit more annoying.  One tool in pyNastran, I find really useful is `test_bdf`.  I run it and it tells me almost everything wrong with my deck.  The Case Control Deck part is very lacking though because the parser is too loose.

The goal of subcase_cards.py was to replace the current approach with a more structured reader.  I backed off a bit from using subcase_cards.py just to maintain backwards compatibility.  Not opposed to it, but it just wasn't quite done.  I'm pretty sure it's barely used.

So depending on much you want to refactor, I'm on board.  I run the Nastran TPL examples, which gives you many, many test problems.  If you'd like a lot of test cases, just add some paths to `pyNastran/bdf/test/tests/foldersRead.txt` and it'll dig through and search for BDF/DAT files.  You can then run `pyNastran/bdf/test/bdf_test.py`.

**Comment by mjredmond** [comment]
This might take me some time... in the mean time I created a pull request to shallow copy the default subcase.  I added a unit test that I believe satisfies your concerns.  Thanks.

**Comment by mjredmond** [comment]
Since you accepted my pull request, I don't have a real need to refactor the case control deck.  I might do it in the future, but it's not a priority for me.  My personal priority is the h5 stuff, so I'll be doing some work on that.
