### ISSUE TITLE
Feature Request - automatic creation of gap elements and fasteners

### ISSUE THREAD

**Issue by mjredmond** [SteveDoyle2/pyNastran#461]
I've done this before, and it's not too hard.  It would be nice to have it in pyNastran.  The gap elements could be either linear or cgaps depending on user option.

1.  define groups of parts
2. auto detect contact regions based on element normal vectors and some distance tolerance defined by user
3.  from part a, project nodes onto part b, rbe3 projected node onto part b using appropriate weights
4.  connect part a to part b with gap element

for fasteners, similar idea

1.  define groups of parts
2.  the user would have to provide information for each fastener created, in general (and maybe later some smart algorithm could auto generate based on some fastener pattern)
3.  user provided information would be part stackup, and a line that defines the fastener if not auto generated
4.  code would project points and rbe3 them to the parts as needed to stitch the fasteners in (or if nodes found within a tolerance just use existing nodes)

I could probably work on this myself but I don't have time right now.  I just wanted to throw the idea out there.

**Comment by SteveDoyle2** [comment]
I think my first question is what types of geometries are you targeting? Projecting nodes based on the element normal can be imprecise unless it's a solid body.  Body A might use a -normal and body B use a +normal.  A shell body can have a contact face on the upper or lower surface.

There are methods though for creating connections based on similar meshes (this case) as well as dissimilar meshes (put a CONM2 at some xyz and rigidly connect it to the 1 to N) closest nodes.  The step of making an RBE or an MPC vs. anything else is not handled because there is a lot of easy custom code required vs needing to sift though code looking for your exact case.

Regarding CGAPs, I've never made those, but don't thet need to be coincident?  Also, the contact family cards (e.g., BCTSURF, BCTBODY) would be nice.  Again, I've never used them.  My MSC Nastran is pretty ancient and NX doesn't have them.

**Comment by mjredmond** [comment]
I'm targeting shell elements.  I've done this before with reasonably good results.  The ways I've done it before was create contact when either face is within a certain distance tolerance from another face whose elements are normal to each other within a certain angle tolerance.

I was envisioning something that would take 2 groups or bodies of elements and gap them when given a tolerance for distance and tolerance for the normal angularity.  

CGAP nodes don't need to be coincident, in fact I prefer them not to be since then you don't have to define a coordinate system and makes them more predictable in behavior.  I'm not able to use BCBODY or any SOL 400 stuff (can only use 106), so I'm stuck with CGAPs.

If it's not a good fit in pyNastran that's ok.  I can just make a separate utilities module.

**Comment by SteveDoyle2** [comment]
I'm not opposed to it.  I'm just trying to understand it and also allow for variations because different people want to do different things that are all slightly different (e.g., `find_closest_nodes` can be used to make MPCs, RBE2s, RBE3s, etc.).  It was originally just used to make RBE2s.  I'm just trying to avoid a giant function with 30 arguments; I think a series of smaller ones would be more useful.

One easy and fast way to do the problem is to transform the nodes in the two groups into a common coordinate system.  Then you can ditch the normal and the piercing and replace it with the z direction.  It also makes inconsistent normal issues go away.  The disadvantage is it can't handle complex surfaces like gear teeth, but for flat, cylindrical, or spherical surfaces, it should be more robust.

The next challenge is what's the best way to handle dissimilar meshes.  CGAPs connect two nodes and presumably you want them to be perpendicular.  You could just find a close node and make it not perpendicular or you could RBE2 the node to the surrounding nodes on the CQUAD4/CTRIA3.

Your idea on fasteners also sounds interesting and I think for that I'd definitely take the user-defined coordinate system option vs. using the surface normal.  In that case, you could define a reference point (e.g., the corner of a 3x4 set of bolts or the center of a circle) and then define the xy's of the bolt locations in some coordinate frame.  That way you could support some complex bolt patterns and rotated patterns.  You could also have simpler patterns that don't require a numpy array for input.  Again, you run into the dissimilar mesh issue.

I think it really needs some realistic examples.

**Comment by mjredmond** [comment]
I don't need this right now and I don't have time for it, so I'm going to close the issue for now.  Thanks.
