### ISSUE TITLE
write_bdf() error

### ISSUE THREAD

**Issue by georgehandrew** [SteveDoyle2/pyNastran#467]
Dear Developer,

Please try the attached *.nas file in the zip with the following code, I got several issues.
```
def ShifitModel(model,shift_vec):
	for nid,node in sorted(model.nodes.items()):
		pos=node.get_position()
		pos_new=pos+shift_vec
		node.set_position(model, pos_new)

nas_fn=r'c:\smallsphere.nas'
nas_fn_out=r'c:\smallsphere2.nas'
model= BDF()
model.read_bdf(nas_fn,xref = False,punch=True)
model.cross_reference(xref=False,xref_nodes=True,xref_elements=True,xref_nodes_with_elements=True)
ShifitModel(model,[0,0,1e-3])
model.write_bdf(nas_fn_out,size=16,is_double=True)
```
several issues:

1. several simulation tools can export nastran file with 'BEGIN BULK' line, pyNastran read_bdf() will fail
2. some simulation tool will export nastran file with blank line,read_bdf() will fail(not show here).
3. write_bdf will fail on this file, with the error ''GRID' object has no attribute 'cp_ref''

[smallsphere.zip](https://github.com/SteveDoyle2/pyNastran/files/1605462/smallsphere.zip)

The first 2 issues are not big problem, but annoying. the 3rd one I don't know how to get rid of it.
BTW, it seems I didn't find the node object has the UpdatePosition member function as described here
http://pynastran-git.readthedocs.io/en/latest/manual/bdf_user.html?highlight=UpdatePosition
it seems it should be something like node.set_position(model, array([1.,2.,3.]), cid=3) %

Thank you very much!

**Comment by SteveDoyle2** [comment]
> several simulation tools can export nastran file with 'BEGIN BULK' line, pyNastran read_bdf() will fail

pyNastran works on a valid Nastran deck, and specifically an NX or MSC Nastran deck.  If your model runs in that solver, then it should work in pyNastran.

Your example has no solution, case control, loads, constraints, properties or materials. 

Another option is to remove the `BEGIN BULK` and call `read_bdf` with `punch=True`.  Alternatively, write `$ pyNastran: punch=True` at the top of the file that doesn't include `BEGIN BULK`.

The issue is BDFs can get very complicated and guessing leads to very strange errors.

> some simulation tool will export nastran file with blank line,read_bdf() will fail(not show here).

I don't 100% follow, but I think that's the case where you want `punch=True`.

> write_bdf will fail on this file, with the error ''GRID' object has no attribute 'cp_ref''

Do you have an example?  I'm getting the following error.

    pyNastran.bdf.errors.MissingDeckSections: This is not a valid BDF (a BDF capable of running Nastran).

    The following sections were found:
     - Executive Control Deck

    The following sections are missing:
     - Case Control Deck
     - Bulk Data Deck

    If you do not have an Executive Control Deck or a Case Control Deck:
      1.  call read_bdf(...) with `punch=True`
      2.  Add '$ pyNastran : punch=True' to the top of the main file
      3.  Name your file *.pch

    You cannot read a deck that has an Executive Control Deck, but
    not a Case Control Deck (or vice versa), even if you have a Bulk Data Deck.

>  I didn't find the node object has the UpdatePosition member function as described here

Thank you for that.  That's outdated.

**Comment by georgehandrew** [comment]
Dear Steve,

Thank you very much for reply.
For the issues 1,2 I mentioned, I understand they are not big headache, I can just remove the BEGIN BULK or blank line or just add the '$' at the beginning of the line, but I hope pyNastran can support these features smoothly, since I saw quite a few simulation tool can generate these kind of nas files.

For the 3rd issue, you can just put the smallsphere.nas in the zip to any directory or 'c:\\' as to be consistent with my code I pasted on the top floor. when run the code, and you will see the error message from `write_bdf()`.
After all, I found that pyNastran seems the only available sophisticated open source tool to handle pyNastran. I hope it could be even better.

**Comment by SteveDoyle2** [comment]
> since I saw quite a few simulation tool can generate these kind of nas files.

I've never seen that.  Other than COSMOL, do you know the names of these codes, so I test it.  You can also make a main bdf file and just use an INCLUDE.

> For the 3rd issue, you can just put the smallsphere.nas in the zip to any directory or 'c:\' as to be consistent with my code I pasted on the top floor. when run the code, and you will see the error message from write_bdf().

I ran `test_bdf smallsphere.nas`, which loads the model and compares it to itself after reading/writing it.  Do you know what version that you're using?  That error message has been there since 2016/12/8, so before 1.0 and the IO has been pretty static since then.

**Comment by SteveDoyle2** [comment]
> so user can easily manipulate the mesh from the nas file just like to manipulate the stl file.

It's funny you mention the STL.  The STL reader needs work to say the least.  It should break things out by region instead of putting them into a single model.

> And since it is mainly for sharing the geometry information, they usually lack of detailed material and properties sections, probably only have a material and/or properties id in element description. I hope pyNastran can be a wonderful tool to handle this kind of nas file,

You can load a BDF though without materials and properties.  You just need to tell it not to cross-reference the elements.  If you really want to do that, you can loop through and add a few extra dummy properties/materials based on what property ids/element types you found.

safe_cross_reference will be able to do that soon, but there are a lot of elements.

**Comment by georgehandrew** [comment]
Dear Steve,

Thank you very much for your quick reply, really appreciate that. Apologize if I said anything wrong or not proper, I really have very little knowledge on nastran.

1. For the simulation tools generate nas file with 'BEGIN BULK', I notice comsol and ansys FE Modeler will have that. Yesterday I thought hypermesh also does that besides it generate blank lines, but actually I am wrong, it only produce the blank line.  I don't quite understand 'You can also make a main bdf file and just use an INCLUDE.' What is this for?
2. I used pyNastran 1.0.0, I think I installed with pip -install... do you mean you can run my code without any error with `write_bdf()`? I notice that after I do `node.set_position(model, pos_new)` in my code, the cp value in the each node in the model.nodes array is changing from 0 to something like `CORD2R         0              0.      0.      0.      0.      0.      1.              1.      0.      0.`, and it seems let the `write_bdf()` throw the error. For more detail, it comes from the last sentence of `Cp()` function in `class GRID`
```
    def Cp(self):
        """
        Gets the analysis coordinate system

        Returns
        -------
        cp : int
            the analysis coordinate system
        """
        if isinstance(self.cp, integer_types):
            return self.cp
        return self.cp_ref.cid
```

3. sorry about using stl as an example, I just mean I hope pyNastran can provide very easy api to operate the incomplete nas file, but I really don't know much about nastran file structure, so I will learn and see. And thanks for the suggestions.

**Comment by SteveDoyle2** [comment]
> Apologize if I said anything wrong or not proper, I really have very little knowledge on nastran.

No worries.  I'm just trying to let you know that pyNastran is really geared towards Nastran users, so there are a lot of things that are just assumed, such as:
 - you know what a GRID vs. an SPOINT is and it doesn't bother you that they're both nodes, despite an SPOINT not technically having a position
 - how to run a static and modal solution at minimum

> You can also make a main bdf file and just use an INCLUDE.' What is this for?

If I make a file called `fem.nas` that looks like:

    SOL 101
    CEND
    SUBCASE 1
        DISP(PRINT,SORT1) = ALL
    BEGIN BULK
    INCLUDE 'smallsphere.nas'

Your problem should load in.

Another thing I noticed was, the following line won't do anything because `xref=False`.  That's why you're not getting `cp_ref`.
   
    model.cross_reference(xref=False, xref_nodes=True, xref_elements=True, xref_nodes_with_elements=True)

This is closer to what you want.  You can't set `xref_elements=True` without properties and materials.
   
    model.cross_reference(xref=True, xref_nodes=True, xref_elements=False, xref_nodes_with_elements=True)

Not sure on `xref_nodes_with_elements` without `xref_elements`; never tried it.

**Comment by georgehandrew** [comment]
Dear Steve,

Thank you for your instructions. It works. And it seems more clear to me now.
