### ISSUE TITLE
pyNastran installation test

### ISSUE THREAD

**Issue by nlgyro** [SteveDoyle2/pyNastran#502]
hello,

I'm new to pyNastran so please bear with me if my question sounds too simplistic.

I've installed pyNastran (v1.0.0) with the latest version of Anaconda per the installations instructions using "python setup.py develop"

I've tried to test the installation using "python setup.py test" and get the following ERROR msg's. (see attached file PyNastran_Error_Msg.txt)

Can you help me out with this?

Thanks,
nlgyro

[PyNastran_Error_Msg.txt](https://github.com/SteveDoyle2/pyNastran/files/1912314/PyNastran_Error_Msg.txt)

**Comment by SteveDoyle2** [comment]
It's complaining about you not having vtk installed, which is only required
for the gui.  I think all you need to do is type:

conda install vtk

I believe you want vtk 6 or 7 for python 3 for v1.0.  Vtk 8 won't work.

**Comment by nlgyro** [comment]
Thanks for the reply.

Should the "conda install vtk" be run at the pyNastran root directory? (i.e D:\Anaconda3\Lib\site-packages\pyNastran-1.0.0)

**Comment by SteveDoyle2** [comment]
It doesn't matter.  Any folder is fine

**Comment by nlgyro** [comment]
okay so I've installed VTK 7.1.0 and when I run the test it doesn't complain about any missing modules but I still get error msg's of a different kind. 

I'm using the procedure laid-out in the install.txt file found in ..\pyNastran-1.0.0\docs\quick_start\ folder.

Attached is the output from DOS on running 'python setup.py test' after installing VTK.

[PyNastran_Error_Msg.txt](https://github.com/SteveDoyle2/pyNastran/files/1913064/PyNastran_Error_Msg.txt)

**Comment by SteveDoyle2** [comment]
I'm not sure what's going on with the gui errors as they passed all the
tests when I released it.  Most of pyNastran 1.0 is compatible with Python
2/3, but gui really works best in Python 2.7 with PyQt4.  The master
version is far more lenient about which versions of Python/PyQt you're
using.

There are also some pandas that are due to running numpy >= 1.13.  Based on
the messages, it looks like you're using numpy 1.14 instead of 1.12.  If
you don't want to use the pandas functionality, it's not a problem.

**Comment by nlgyro** [comment]
your installation notes specify numpy>=1.11.0 & hence I use numpy 1.14 which comes along with the latest version of Anaconda. 

I'll try using the master version and revert back.
