### ISSUE TITLE
Reading bdf´s with sets is really slow

### ISSUE THREAD

**Issue by AlejandroStewart** [SteveDoyle2/pyNastran#560]
hello,

 I have noticed that reading bdf files using read_bdf() method takes really long
when set definition as follows is used for big sets.

_SET 1 = 63911,63912,63913,63914,63915,63916,
        63917,63918,63919,63920,63921,63922,
        63923,63924,63925,63926,63927,63928,
        63929,63930,63931,63932,63933,63934,
        63935,63936,63937,63938,63939,63940,
        63941,63942,63943,63944,63945,63946,
        63947,63948,63949,63950,63951,63952,
        63953,63954,63955,63956,63957,63958,
        63959,63960,63961,63962,63963,63964,
        63965,63966,63967,63968,63969,63970,_

When using THRU I see no lag.

Thank you

**Comment by SteveDoyle2** [comment]
It’s the same function, so I’m not really sure.  That set is literally just a for loop over integers as well as piecing the lines together (you can put it all on one line to make it easier to write if you’re going to rewrite it anyways, which is ever so slightly faster). 

 I’ve been working on set parsing lately to read more types of sets and it’s instantaneous from what I’ve seen.  Of things that are slow during BDF reading, sets shouldn’t be one of them.

Did you test it with timeit?

**Comment by AlejandroStewart** [comment]
I have profiled the read method for both versions of the set, 

From what i see it points to _subcase_utils.py:60(expand_thru_case_control)_

there is a loop _for ivalue in set_value:_ that is done once in the case of THRU and once per element when using coma separated elements

I have added the following code just above and the execution time goes back to normal:

    has_thru_statement=True in ['TRHU' in val.upper() for val in set_value]
    if not has_thru_statement:
        [set_value2.add(val.strip()) for val in set_value]
        set_value=[]# skip loop



I am sure there is a mor elegant solution, but the idea is there





[profile_long_set.txt](https://github.com/SteveDoyle2/pyNastran/files/3228079/profile_long_set.txt)
[profile_short_set_set.txt](https://github.com/SteveDoyle2/pyNastran/files/3228080/profile_short_set_set.txt)
[profile_long_set_with_fix.txt](https://github.com/SteveDoyle2/pyNastran/files/3228255/profile_long_set_with_fix.txt)

**Comment by SteveDoyle2** [comment]
TRHU should be THRU.

There really shouldn't be an issue with that for loop.  Even for a large number of values, it's still a simple loop.  What it seems you're really getting the advantage from is not casting the data.

The function `expand_thru_case_control` is also getting replaced with `expand`, which is more capable.  In the trunk, both are being run on every problem and if there's a difference, there's an error.  If `expand` passes, but `expand_thru_case_control` fails, that's OK, but not vice versa.

**Comment by SteveDoyle2** [comment]
Also, that function handles things other than just integers, so floats, ALL, 123/R1, etc.  It's not easy to just make a modification to check if it does or doesn't have THRU.  That's why that function needs to go.

**Comment by SteveDoyle2** [comment]
Can you attach the full test problem, rather than an abbreviated problem that runs instantaneously?  You didn't mention it was 406 seconds to parse a SET.

**Comment by SteveDoyle2** [comment]
I made a test using various set parsing methods.  They're not entirely fair as there's sometimes an additional split method, but I think it's fair enough.  I think the fundamental issue is the interpret_value function, which is needed for that method, but there are clearly better ways to handle things like that.

## for 1000 values
dt (expand) = 0.0009718
dt (expand_thru) = 0.0010219
dt (expand_thru_case_control) = 0.0638 (65x over expand, 62x over expand_thru)

## for 10,000 values
dt (expand) = 0.00698
dt (expand_thru) = 0.01296
dt (expand_thru_case_control) = 6.297 (902x over expand, 485x over expand_thru)

## for 1,000,000 values
dt (expand) = 0.778
dt (expand_thru) = 0.738
dt (expand_thru_case_control) = ??? I've waited at least 20 minutes...we'll see tomorrow...

Running the 10k test twice shows the numbers aren't super accurate (I think expand and expand_thru are closer), but it's in that range.  So, clearly the method is really bad.

**expand** is sort of the new beta method for **expand_case_control_deck**.  It pass all the tests that I've thrown at it.  I still have some confusion over cases like 1 THRU 10 EXCEPT 2,1,2 on whether or not the 2 is included, but that's sort of a B-list option.  It's important for the TPL problems, but not much else.  There are also some error conditions that I don't understand how to trigger, but I'd be surprised if they're aren't hit at some point.

**expand_thru** is what's used for the BDF and doesn't support things like multi-type (e.g., floats, 123/R1) BY, EXCLUDE, or mixed commas/spaces.  It's sort of an estimate of the fastest things could possibly be.

**expand_case_control_deck** it turns out has a bug in the parsing of 1 THRU 10 BY 2, so I'm just going to kill it in favor of **expand**.  The crazy thing is is that method's not even optimized.

It's not pushed yet though.  There are some other bugs I need to get rid of first.

**Comment by SteveDoyle2** [comment]
16 hours later, it's still going.  I'm curious to see how truly bad it is.  It's currently at 1300x.

I've pushed the fix though.  I'll do some cleanup later and rename **expand** to **expand_case_control_deck**.  Given how terrible it is, I think it needs backporting.

**Comment by SteveDoyle2** [comment]
76460 seconds = 21.2 hours, so 98,290x slower than expand.  My math before was wrong :/

**Comment by AlejandroStewart** [comment]
Sorry I didn´t see you asked for a test problem untill now.
 Glad you managed to solve it, thank you.

**Comment by SteveDoyle2** [comment]
No worries.  Once I found out how slow it was by reading the profiling
output, I just made a really simple problem.

Thanks for finding it!
