### ISSUE TITLE
OP2 and solver versions

### ISSUE THREAD

**Issue by DenisWalch** [SteveDoyle2/pyNastran#623]
Hello,

The code of pyNastran.op2.op2_interface.op2_reader
includes a list of different optistruct solevr versions
OPTISTRUCT_VERSIONS = [
    b'OS11XXXX', b'OS12.210', b'OS14.210',
    b'OS2017.1', b'OS2017.2',
    b'OS2018.1']

As I am running OptiStruct 2019.1, the code does not work...
Once I understood the bug, the fix is easy by adding the 'OS2019.1' item in the list. 
When I contacted Altair, they told me they are trying to keep as much traceability as possible within the op2 file with respect to the solver version.
Everytime a new version will be released, they will include a new tag. Maybe a more generic tag might be useful to avoid keep up with these updates ?

Thanks for your work. I like this library very much.
Denis

**Comment by SteveDoyle2** [comment]
Thanks for that.  I've been pretty busy, so I let this lag a bit.

Every format that pyNastran supports (MSC, NX, OptiStruct) has changed their versioning scheme over the years.  I'm trying to collect that list of versions, so the code not working on unsupported things is intentional.  I'm all for Altair's support to improve that list/the many other things that are probably not right, but I don't have that help.  If something isn't expected, I'd prefer it to stop so I can see it rather than potentially give the wrong answer.

**Comment by DenisWalch** [comment]
Hello Steve,
No worries,What you have done is absolutely amazing.I am using it often and very happy about it.
Now I know what to change in the occurence of a new version, very easy to upgrade.
Thanks for your work.
Denis
    Le mardi 6 octobre 2020 à 11:42:52 UTC−4, Steven Doyle <notifications@github.com> a écrit :  
 
 


Thanks for that. I've been pretty busy, so I let this lag a bit.

Every format that pyNastran supports (MSC, NX, OptiStruct) has changed their versioning scheme over the years. I'm trying to collect that list of versions, so the code not working on unsupported things is intentional. I'm all for Altair's support to improve that list/the many other things that are probably not right, but I don't have that help. If something isn't expected, I'd prefer it to stop so I can see it rather than potentially give the wrong answer.
