### ISSUE TITLE
Error reading OP2: UNITS & custom table

### ISSUE THREAD

**Issue by martinglu** [SteveDoyle2/pyNastran#647]
During reading a op2 file the program crushes due to some mismatch of the UNITS table. I have no overview of the op2 data structure, therefore I did not succeed to fix it. Do you have an idea for a workaround ? Thanks.

DEBUG:   op2_scalar.py:1959             table_name=b'UNITS'
WARNING: op2_reader.py:3969           unexpected tout for b'UNITS': matrix_num=101 form=32767 mrows=32767 ncols=32767 tout=32767 nvalues=32767 g=32767
  code = (541542221, 538976288, 538976334)

ndata = 32:
  strings = (b'MGG     N       MM      S       ',)
  ints    = (541542221, 538976288, 538976334, 538976288, 538987853, 538976288, 538976339, 538976288)
  floats  = (1.687954709992453e-19, 1.3563156426940112e-19, 1.356321588054664e-19, 1.3563156426940112e-19, 1.3578103839102886e-19, 1.3563156426940112e-19, 1.3563222342895175e-19, 1.3563156426940112e-19)

RuntimeError: unexpected tout for b'UNITS': matrix_num=101 form=32767 mrows=32767 ncols=32767 tout=32767 nvalues=32767 g=32767

**Comment by SteveDoyle2** [comment]
Do you have a small example?

**Comment by martinglu** [comment]
It seems that this related to an op2 file with none typical tables. I made a simple nastran example, where I could run it. So, I try to make an simple example with the same op2 structure, then I will come back to you.

**Comment by martinglu** [comment]
I created a simple example, which reproduces the error.  Do you have an idea to read the UNITS table and the additional table properly ? thanks.
[twomassspringdamperexample.zip](https://github.com/SteveDoyle2/pyNastran/files/6478736/twomassspringdamperexample.zip)

**Comment by SteveDoyle2** [comment]
What version of MSC do you have?  The UNITS table doesn't match what I'm seeing.  I see:

    'MGG', 'N', 'MM', 'S'

but the documentation has:
![image](https://user-images.githubusercontent.com/1059417/118310796-eafc3c00-b4a3-11eb-8fa2-eba81aca999e.png)

Also, what is the CPHSF table?  There is no documentation for it.

**Comment by martinglu** [comment]
It was MSC 2017. But units are megagram (MGG,1000kg) and MM (millimeter, 1e-3 m), it is foreseen in the MSC reference guide of the DTI command.

Indeed, CPHSF is a own made table. Is it possible to implement individual table, for example by defining the size ? Thanks.

**Comment by SteveDoyle2** [comment]
Ahhh...I assumed the MGG was the MGG matrix.  It's should be Mg (megagram) and milligram (mg), but Nastran loves all caps :)  DTI,UNITS will be accessible with the geometry flag (since it makes the DTI,UNITS).

> Is it possible to implement individual table

Yes.  I'm sure you've seen the following message:

```
If you have matrices that you want to read, see:
  model.set_additional_matrices_to_read(matrices)  
  matrices = {
      b'BHH' : True,
      b'KHH' : False,
  }  # you want to read some matrices, but not others
  matrices = [b'BHH', b'KHH']  # assumes True

If you the table is a geom/result table, see:
  model.set_additional_result_tables_to_read(methods_dict)
  methods_dict = {
      b'OUGV1' : [method3, method4],
      b'GEOM4SX' : [method3, method4],
      b'OES1X1' : False,
  }

If you want to take control of the OP2 reader (mainly useful for obscure tables), see:
  methods_dict = {
      b'OUGV1' : [method],
  }
  model.set_additional_generalized_tables_to_read(methods_dict)
```

So depends on what you mean by "table".  I/other people use the word table fairly loosely.  A matrix is the easiest thing to add, but it needs to be a Nastran-matrix (and not say an OUGV1/displacement table) or FOL/MKAERO table.

The OUGV1 table (e.g., displacements) is more dynamic and has a subcase info (e.g., time/mode/freq, various flags), and then results.  The table 3 function is for subcase info and the table 4 part has the data.  It's definitely not for the faint of heart.

The FOL (frequency list) and MKAERO (mach, reduced frequency) tables are technically matrices, but not written as one.  They've got they're own custom format.  For that you'd use the 3rd option.  You are expected to read the entire table, but generally they're fairly simple tables (e.g., just reshape 2N values into a (N,2) shape).  My guess is this is what you have.

**Comment by SteveDoyle2** [comment]
fixed and testd a while ago
