### ISSUE TITLE
data_in_material_coord not working 

### ISSUE THREAD

**Issue by chvisser98** [SteveDoyle2/pyNastran#679]
I would please like to request assistance with using the data_in_material_coord function. I have attempted to implement its functionality in a very basic FEM example, before implementing it in my main work, although it fails to produce the desired result (of converting my results to the material coordinate system). When I implement it as below (in the attached image of my code from a Jupyter Notebook), it produces the same results as it would without using the function. When I view the corresponding .f06 file results though, I see that the correct results are indeed there, so I am unsure why after using the function that my .op2 results do not match. 

Any clarification/assistance would be greatly appreciated.

![image](https://user-images.githubusercontent.com/74358814/151943868-85ed0112-6f33-4610-837a-4e7ddc01d219.png)

**Comment by SteveDoyle2** [comment]
I'd need to see an example.

**Comment by chvisser98** [comment]
Thank you very much for the response @SteveDoyle2.

These are the results obtained from the .op2 file (from the code in the attached image in my previous comment), which are the same as those obtained without implementing the function.
![image](https://user-images.githubusercontent.com/74358814/152048863-0d15a2f0-e32f-45f5-9c84-643cf9d32b22.png)

Below is an extract of the results obtained from the .f06 file, which are the results in the material coordinate system (I confirmed this in the FEM analysis I did) and are the results I am attempting to obtain from the .op2 file.
![image](https://user-images.githubusercontent.com/74358814/152049672-4eed7cb6-a78d-4279-bb50-d9e1e4791591.png)

If any other examples are needed, please do inform me (as well as what format is easiest).

**Comment by SteveDoyle2** [comment]
A screenshot is not enough.  I can't do anything with that.

I need a 1 element problem with whatever made up materials and load that shows it's different.  I need the bdf, f06 and op2.

**Comment by chvisser98** [comment]
Sorry once again, I thought that there was perhaps someone evidently wrong with my code, but I understand what you mean now. Attached is a .zip file with the .bdf, .f06 and .op2 files as requested. I attached the original .bdf file obtained from my FEM analysis (in MSC Patran) as well as the .bdf file generated for the (new) model, as in the code above. If any of the needed information is not available in the attached files, please do inform me and I shall provide you with it as well. 

[CoordSysTest_new.zip](https://github.com/SteveDoyle2/pyNastran/files/7983826/CoordSysTest_new.zip)

**Comment by AlejandroStewart** [comment]
For reference: https://github.com/SteveDoyle2/pyNastran/issues/630

**Comment by SteveDoyle2** [comment]
[coordsystest_new.test_op2.bdf.txt](https://github.com/SteveDoyle2/pyNastran/files/7984468/coordsystest_new.test_op2.bdf.txt)

At least superficially, the theta matches for elements [1, 2, 3, 4, 5, 6, 7, 8] with what's written in the op2.

array([-14.03624347, 165.96375653, -14.03624347, 165.96375653,
       -14.03624347, 165.96375653, -14.03624347, 165.96375653])

Not sure...tomorrow's problem.

**Comment by chvisser98** [comment]
Thank you for the advice @AlejandroStewart, although I had looked at #630 before and it, unfortunately, did not assist with my issue (I am working with Cartesian coordinate system and not cylindrical as I see you have).

Thank you for the assistance thus far @SteveDoyle2. I opened the file you attached in your comment and see that it has the THETA values listed for each element, although in my case, both my .bdf files have the MCID listed instead ("0" in my case). Not sure if it is perhaps relevant to the problem, although I thought it may be worth mentioning, as I was curious how you generated the file on your side as well. Any further assistance/feedback from your side would be greatly appreciated and please do let me know if there is anything further that I can do from my side.

**Comment by SteveDoyle2** [comment]
Fat fingers :)

That command reads the op2, pulls the geometry, and just writes it.  I was
surprised to see the mcid had been transformed to theta.  I suspect it’s
because you requested a transform.

So case 1 for the coordinate systems is using a float.  0 degrees is
defined along 1-2.  You can cross that with the normal to get j.  It is a
local “cylindrical” coordinate elemental system (pretend you have a PCOMP
and are defining ply angles).  This is what’s referred to as the element
coordinate system.

 I say it’s cylindrical because I’m typically working with ply angles/some
kind of rotation, but it has no inherent type.

The other approach uses the projection of the x axis of a CORD1/2x (mcid)
onto the element (a CORD2R vs COR2C doesn’t matter).  Cross that vector x
with the normal to get j.  Cross j with the normal to get I.  Again, it’s a
local “cylindrical” elemental coordinate system and is the material
coordinate system (The material coordinate system is not cid=0).  From
there, you can get the rotation angle from the element coordinate system to
them material coordinate system.

I didn’t write the function, but it figures out the equivalent theta for
the mcid elements and then rotates the output.  So far, the result from
step 1 seems fine.

**Comment by chvisser98** [comment]
Thank you for the thorough explanation, I believe I mostly followed it and it provided some useful further insight into the problem. 

Not sure if it makes a difference, but I see that you said "The material coordinate system is not cid=0" which I do understand, although in my case when I set up my FEM analysis (in MSC Patran) I specifically set my "Material Orientation" to be in the same coordinate system as my global coordinate system whose CID="Coord 0". This then meant that when I probed results (in MSC Patran) in both the material and global coordinate systems, I obtained the same results, which was my desired intention. Not sure if this has any relevance to our problem at hand, although I feel as though it may be worth mentioning nonetheless.

**Comment by SteveDoyle2** [comment]
MCID is the coordinate system you’re projecting onto the element to create
the element material coordinate system.  The distinction matters at this
level, but Patran glosses over it.

All that matters is what angle the projected x of the mcid is with the
element coordinate system.  Let’s say you have a plate inclines at 45 to
the mcid with a Sigma xx and yy.  Sigma ZZ is still 0 after the transform.

**Comment by chvisser98** [comment]
Thanks again for the explanation @SteveDoyle2, I believe I am still following you mostly as well. So do I understand correctly that the issue I have is not a result of how I define my "Material Orientation" in Patran and therefore what the MCID is set as?

**Comment by SteveDoyle2** [comment]
Yes.

**Comment by chvisser98** [comment]
Okay, thanks @SteveDoyle2. Any ideas perhaps yet on where my issue may be? I am open to any suggestions, although if you are still unsure at the current time, I shall continue waiting patiently for feedback.

**Comment by SteveDoyle2** [comment]
I haven't had any more time to look at it.  It's probably step 2.

**Comment by SteveDoyle2** [comment]
It still needs some work, but your immediate issue was caused by accessing the original dataframe after the transformation.

if you set `build_dataframe=False` and then after the transform call:
  - op2_new.build_dataframe()
Alternatively, you can just call `ctria3_strain.build_dataframe()`.  I'm going to fix that (just recalculate it automatically if you have a dataframe), but it's not pushed.

There's another issue, which I think only happens when you have a CTRIAx and CQUADx with MCID, which seems like it'd be pretty common.  I basically rewrote the loop to calculate that and it's giving me wrong answers on the original test problems...

**Comment by SteveDoyle2** [comment]
The CTRIA3/CQUAD4 MCID bug I mentioned (again not the original issue) is fixed.  

Also, build_dataframe is now automatically re-called if a dataframe exists, though your code will be slightly faster if you call build_dataframe after the transform and not as part of the read_op2 step.  You may want both though (and it's super confusing to have it not be current), so...
