### ISSUE TITLE
nastran_to_vtk BUG

### ISSUE THREAD

**Issue by karma0704** [SteveDoyle2/pyNastran#773]
Hello, gentleman! When I call nastran_to_vtk to complete the export of 64-bit bdf and op2 files into VTK files, the export cannot be performed normally. It may be that the data parsing is incorrect. I used the 32-bit version of the same file to test and found that the 32-bit file was normal. In contrast, I found that there were differences between the 32-bit and 64-bit files when processing the CompositeStrainStressResults2 object. The 64-bit input is as shown below: 
![image](https://github.com/SteveDoyle2/pyNastran/assets/63630092/dfd90b1c-8d90-4115-9839-0766d52028ac)

Because of this The error caused "" to be thrown
![image](https://github.com/SteveDoyle2/pyNastran/assets/63630092/f1e8498d-72cd-4bdb-b721-edc958ae5cc1)

I don't know how to fix this problem fundamentally. If I could understand it better, I could fix it, but not now. I have provided the test demo before, and it should be available in models now.

**Comment by SteveDoyle2** [comment]
It's fixed.  So I thought that was disabled, but it was on.

It was also listed as itime instead of iresult.  Basically, there's say 6 results, [oxx, oyy, txy, omax, omin, max_shear].  These are listed as iresult=0 -> 5.  You can also calculate von_mises, so it uses a string to flag that it's not in the data array.
